# -*- coding: utf-8 -*-
"""CCFraudproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HX3s1O5268r9cP-Iewh7etz_wX9gu7Xc
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

fi=pd.read_csv("/content/creditcard[1].csv")
print(fi)

fi.isnull().sum()

fi.dropna(inplace=True)

scaler=StandardScaler()
#the 'Amount' column has large variance while V1-V28 columns are clustered near 0
#used StandardScaler to normalize the transaction amounts so they dont skew the algorithm

fi['Scaled_Amount']=scaler.fit_transform(fi['Amount'].values.reshape(-1,1))
#reshaped the data cos the scaler requires a 2D array
fi.drop(['Time','Amount'],axis=1,  inplace=True)
#dropped original 'Amount' column and 'Time' column as it does not add predictive value for this specific classification model

x=fi.drop('Class',axis=1)
y=fi['Class']
#'x' contains all the independent vars (transaction details)
#'y' contains the target var (0 for Normal Transaction, 1 for Fraudulent)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

model=LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
model.fit(x_train,y_train)
#'class_weight='balanced' ' is most imp parameter, it mathematically adjusts the weights inversly proportional to class frequencies forcing the model to pay strict attention to rare fraud cases
#'max_iter=1000' ensures the algo has enuff iterations to successfully converge on a mathematical solution

y_pred=model.predict(x_test)
#generate binary predictions
y_prob=model.predict_proba(x_test)[:,1]
#extract probability score # sliced [:,1] to keep just the fraud probability as predict_proba returns 2 columns(proba of 0, proba of 1)

#Audit Reporting
#print a conf_matrix & classification_report to audit the models accuracy, precision and recall
print("****** RISK MODEL AUDIT REPORT ******")
print("\n***********************************************************************")
print("\nConfusion Matrix: ")
print(confusion_matrix(y_test,y_pred))
print("\n***********************************************************************")
print("\nClassification Report: ")
print(classification_report(y_test,y_pred))

res_df=x_test.copy()
res_df['Actual_Class']=y_test
res_df['Predicted_Class']=y_pred
res_df['Fraud_Probability']=y_prob

res_df.to_csv("fraud_preds4bi.csv", index=False)
print("\nSuccess: 'fraud_preds4bi.csv' has been generated and is ready for Power BI")